version: "3.9"

services:
  web:
    build: .
    container_name: xss_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: xss_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=xss_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin